# Generated by Django 4.2.5 on 2023-09-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('regNo', models.CharField(max_length=15)),
                ('fingerprint_template', models.BinaryField()),
                ('fingerprint_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
