# Generated by Django 4.2.5 on 2023-09-24 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_student_candidate_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.student'),
        ),
    ]
